# Based on the official Immich release Compose file:
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml

name: my-photo-gallery-immich

services:
  rclone:
    container_name: my-photo-gallery-immich-rclone
    image: rclone/rclone:latest
    restart: always
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./rclone-config:/config/rclone
      - ./rclone-shared-mount:/data:shared
      - D:/Immich/cache:/config/cache
    command: mount my-r2:my-photo-gallery-immich /data --vfs-cache-mode full --cache-dir /config/cache --vfs-cache-max-size 10G --vfs-cache-max-age 1h --allow-other --s3-no-check-bucket --allow-non-empty

  immich-server:
    container_name: my-photo-gallery-immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-v3}
    volumes:
      - ./rclone-shared-mount:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - "6001:2283"
    depends_on:
      - redis
      - database
      - rclone
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: my-photo-gallery-immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-v3}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: my-photo-gallery-immich-redis
    image: docker.io/valkey/valkey:9@sha256:3b55fbaa0cd93cf0d9d961f405e4dfcc70efe325e2d84da207a0a8e6d8fde4f9
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: my-photo-gallery-immich-postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "6002:5432"
    shm_size: 128mb
    restart: always
    healthcheck:
      disable: false

volumes:
  model-cache:
  postgres-data:
